

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.34:1521/orcl
    username: shops
    password: '!a4s5'

server:
  port: 8010

# VO location
mybatis:
  type-aliases-package: src.test.auth.data

# XML location
  mapper-locations:
  - classpath:mappers/**/*.xml
