

spring:
  application:
    name: product-api
  mvc:
    static-path-pattern: resources/static/**
    
    
  # Oracle JDBC
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.34:1521/orcl
    username: shops
    password: '!a4s5'
    
# 첨부파일 저장 경로 설정 :: spring.servlet.multipart.location
  servlet:
    multipart:
      location: C:\Users\fkdlt\git\carrotCopy\e_Product_Server\src\main\resources\static\images
      max-file-size: 10MB
      
# Encoding 설정 :: server.servlet.endoing.charset      
server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
# Eureka Client가 서비스를 등록한 서버 주소 지정 :: eureka.client.service-url.defaultZone
eureka:
  client:
    service-url: 
      defaultZone: http://172.30.1.34:8761/eureka/    
mybatis:
  type-aliases-package: src.test.product.data
  mapper-locations:
  - classpath:mappers/**/*.xml
  


  




