

spring:
  application:
    name: chat-api
    
  output:
    ansi:
      enabled: NEVER
      
server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      